apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstonecluster
  region: us-west-2

nodeGroups:
  - name: green
    labels: { type: green }
    instanceType: t2.medium
    desiredCapacity: 2