apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstonecluster
  region: us-west-2

nodeGroups:
  - name: blue
    labels: { type: blue }
    instanceType: t2.medium
    desiredCapacity: 2