apiVersion: v1
kind: Service
metadata:
#    annotations:
#        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-west-1:xxx:certificate/xxx
    labels:
        app: company2vec
    name: company2vec
spec:
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 80
          targetPort: 5000
    selector:
        app: company2vec-blue
        environment: dev